version: '3'

services:
  hostel:
    build:
      context: ./hostelmgmt-housekeeping
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  course:
    build:
      context: ./intelligent-scheduler
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  smart-content:
    build:
      context: ./smart-content-recommender
      dockerfile: Dockerfile
    ports:
      - "5002:5002"