version: '3'

services:
  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  hostel-registration-attendance:
    build:
      context: ./hostel-registration-attendance
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  
  hostel-menu:
    build:
      context: ./hostel-menu
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
  
  housekeeping:
    build:
      context: ./housekeeping
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  course-scheduler:
    build:
      context: ./intelligent-scheduler
      dockerfile: Dockerfile
    ports:
      - "5004:5004"

  smart-content:
    build:
      context: ./smart-content-recommender
      dockerfile: Dockerfile
    ports:
      - "5005:5005"